version: "3.2"
services:
  # node 1
  centos7:
    build:
      context: ./nodes/centos7
      dockerfile: Dockerfile
    image: ansible-centos7
    container_name: ansible-centos7
    hostname: centos7
    privileged: true
    volumes: 
      - ./ssh/ansible_rsa.pub:/root/.ssh/authorized_keys
  # node 2
  ubuntu16:
    build:
      context: ./nodes/ubuntu16
      dockerfile: Dockerfile
    image: ansible-ubuntu16
    container_name: ansible-ubuntu16
    hostname: ubuntu16
    privileged: true
    volumes: 
      - ./ssh/ansible_rsa.pub:/root/.ssh/authorized_keys
  # node 3
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
  # node 4
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
  # ansible実行環境
  myansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: myansible
    container_name: myansible
    hostname: myansible
    links:
      - centos7:centos7
      - ubuntu16:ubuntu16
    volumes:
      - ./playbooks:/playbooks
      - /var/run/docker.sock:/var/run/docker.sock
